title: "【错误报告】"
labels: bug
name: "🐞 错误报告"
description: 创建报告以帮助我们改进
body:
  - type: markdown
    attributes:
      value: |
        **开始之前...**

        此表单仅用于提交错误报告。如果您有使用问题
        或者不确定这是否真的是一个错误，请确保：

        - 已更新到最新版本
        
        还要尝试搜索您的问题 - 它可能已经在 Issues 中得到解答甚至修复。
        但是，如果您发现旧的、已关闭的问题在最新版本中仍然存在，您应该使用下面的表单打开一个新问题，而不是对旧问题发表评论。
        
  - type: input
    id: version
    attributes:
      label: 你使用的浏览器版本 + 扩展版本号
      placeholder: 如：Chrome 131 / 1.0.1 
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 问题描述
      description: |
        对错误内容的清晰简洁的描述，如果可以的话，尽量提供一些错误截图，比如控制台报错或者页面。
    validations:
      required: true
